name: Build Cloudflared
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - run: git clone https://github.com/cloudflare/cloudflared.git

      - run: cp hello.go cloudflared/hello/hello.go

      - run: |
          cd cloudflared
          GOOS=linux GOARCH=arm64 make cloudflared
          mv cloudflared ../cloudflared-linux-arm64

      - run: chmod +x ./cloudflared-linux-arm64

      - run: mkdir -p ~/.cloudflared; echo 'LS0tLS1CRUdJTiBBUkdPIFRVTk5FTCBUT0tFTi0tLS0tCmV5SjZiMjVsU1VRaU9pSXdaakUzWVdNMU1XRTFNekZrTnpCbVlUTXdNRFZsTWprM05XWmxOalJsTWlJc0ltRmoKWTI5MWJuUkpSQ0k2SWpWbU1EUXdaV0psWVdJek9ERTFZVEEwTldFeU4yTTFPR0poTTJVeVl6UXlJaXdpWVhCcApWRzlyWlc0aU9pSmpablYwWDFSYWNEUlBZamxNYTBseGFWRk5XbVF4YVZWdVNFZHlNbVJRVlVneU1FdFpiVlJKCmRsSlNhMDQwTjJGaU5UY3lOQ0o5Ci0tLS0tRU5EIEFSR08gVFVOTkVMIFRPS0VOLS0tLS0K' | base64 -d > ~/.cloudflared/cert.pem; ./cloudflared-linux-arm64 tunnel delete -f lscf-tunnel || true; ./cloudflared-linux-arm64 tunnel create lscf-tunnel; ./cloudflared-linux-arm64 tunnel route dns -f lscf-tunnel lscf.eu.cc; ./cloudflared-linux-arm64 tunnel run --url hello_world lscf-tunnel
